version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 8
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      lint:
        patterns:
          - eslint*
          - typescript-eslint
          - prettier
      types:
        patterns:
          - '@types/*'
          - typescript
      test:
        patterns:
          - vitest
          - '@vitest/*'
          - '@playwright/*'
          - supertest
      prisma:
        patterns:
          - prisma
          - '@prisma/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /apps/worker
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
