export {
  APPLICATION_ERROR_KIND,
  ApplicationError,
  AuthenticationError,
  AuthorizationError,
  ConflictError,
  ExternalServiceError,
  IntegrityError,
  InvalidStateTransitionError,
  isApplicationError,
  NotFoundError,
  RateLimitError,
  ValidationError,
  type ApplicationErrorDetails,
  type ApplicationErrorKind,
} from './errors.js';
export {
  DOCUMENT_STATES,
  DOCUMENT_REVISION_KINDS,
  DOCUMENT_INSPECTION_STATUSES,
  UPLOAD_SESSION_STATUSES,
  INSPECT_DOCUMENT_JOB_TYPE,
  NOTIFY_SIGNER_JOB_TYPE,
  FLATTEN_SIGNATURE_JOB_TYPE,
  VERIFY_AUDIT_CHAINS_JOB_TYPE,
  SIGNER_STATUSES,
  SIGNING_SESSION_STATUSES,
  SIGNATURE_FIELD_TYPES,
  SIGNING_MODES,
  FIELD_OVERLAP_POLICIES,
  AUDIT_ACTOR_TYPES,
  AUDIT_EVENT_TYPES,
  ACCOUNT_SECURITY_EVENT_TYPES,
  OUTBOX_STATUSES,
  BACKGROUND_JOB_STATUSES,
  JOB_ERROR_CATEGORIES,
  DEFAULT_JOB_MAX_ATTEMPTS,
  IDEMPOTENCY_PRINCIPAL_TYPES,
  type AccountSecurityEvent,
  type AccountSecurityEventType,
  type AccountSession,
  type AccountUser,
  type AuditEvent,
  type AuditActorType,
  type AuditEventType,
  type BackgroundJob,
  type BackgroundJobStatus,
  type JobErrorCategory,
  type ConsentRecord,
  type Document,
  type DocumentInspectionStatus,
  type DocumentRevision,
  type DocumentRevisionKind,
  type DocumentState,
  type FieldOverlapPolicy,
  type FinalizedArtifact,
  type IdempotencyPrincipalType,
  type IdempotencyRecord,
  type Organization,
  type OrganizationMembership,
  type OutboxEvent,
  type OutboxStatus,
  type PreviewGrant,
  type SignatureField,
  type SignatureFieldType,
  type Signer,
  type SignerStatus,
  type SigningMode,
  type SigningSession,
  type SigningSessionStatus,
  type UploadSession,
  type UploadSessionStatus,
} from './entities.js';
export {
  DOCUMENT_TRANSITIONS,
  SIGNING_SESSION_TRANSITIONS,
  assertDocumentTransition,
  assertInspectionAccepted,
  assertPreparationUnlocked,
  assertReadyToSend,
  assertSigningSessionTransition,
  canTransitionDocument,
  canTransitionSigningSession,
  isAvailableForSigning,
  isDocumentState,
  isInspectionAccepted,
  isOpenSigningSession,
  isPreparationLocked,
  isPreparationState,
  isSigningSessionStatus,
} from './document-lifecycle.js';
export {
  assertedSigningMode,
  assertSignerRouting,
  canSignerActNow,
  isSigningMode,
} from './signing-mode.js';
export { assertFieldLayout, assertFieldOnPage, fieldsOverlap } from './field-geometry.js';
export {
  isOpaqueId,
  organizationContext,
  requireOpaqueId,
  requireOrganizationId,
  type OrganizationContext,
} from './organization-context.js';
export {
  actorId,
  actorType,
  MEMBERSHIP_ROLES,
  organizationContextFromActor,
  type AccountUserActor,
  type MembershipRole,
  type RequestActor,
  type SignerActor,
  type SystemActor,
  type WorkerActor,
} from './request-actor.js';
export {
  AUDIT_GENESIS_PREVIOUS_EVENT_HASH,
  artifactObjectKey,
  assertTenantObjectKey,
  signatureImageObjectKey,
  sourceRevisionObjectKey,
  tenantObjectKey,
  tenantObjectKeyPrefix,
} from './object-keys.js';
export type {
  Clock,
  Hashing,
  IdGenerator,
  AuditWriter,
  ClientRequestMetadata,
  ConsentDisclosure,
  ConsentDisclosureCatalog,
  DocumentInspectionOutcome,
  DocumentInspector,
  FlattenedAppearance,
  JobPublishInput,
  JobPublisher,
  NewAuditEvent,
  Notifier,
  ObjectStorage,
  PdfFlattener,
  SigningEnvelopePolicy,
  SigningInvitation,
  SigningTokenGenerator,
  SigningTokenHasher,
  StoredObject,
  StoredObjectMetadata,
  UnitIntervalRandom,
} from './ports/services.js';
export type { AuthenticatedIdentity, IdentityProvider } from './ports/identity-provider.js';
export type { AccountSessionRepository } from './ports/account-session.js';
export type {
  AccountSecurityAuditWriter,
  NewAccountSecurityEvent,
} from './ports/security-audit.js';
export type { RateLimitDecision, RateLimiter } from './ports/rate-limiter.js';
export {
  AUTHORIZATION_ACTIONS,
  type AuthorizationAction,
  type AuthorizationPolicy,
  type AuthorizationResource,
} from './ports/authorization.js';
export type {
  AuditLogRepository,
  BackgroundJobRepository,
  ConsentRecordRepository,
  DocumentRepository,
  DocumentRevisionRepository,
  FinalizedArtifactRepository,
  IdempotencyRecordRepository,
  MembershipRepository,
  OrganizationRepository,
  OutboxEventRepository,
  PreviewGrantLookup,
  PreviewGrantRepository,
  SignatureFieldRepository,
  SignerRepository,
  SigningSessionRepository,
  SigningTokenLookup,
  TenantRepositories,
  UploadSessionLookup,
  UploadSessionRepository,
  UserRepository,
} from './ports/repositories.js';
export { TENANT_REPOSITORY_TYPE_GUARDS } from './ports/repositories.js';
export type { TransactionScope, UnitOfWork } from './ports/unit-of-work.js';
export type { AssertTenantScopedRepository } from './ports/tenant-scope.js';
export { assertSafeJobPayload } from './jobs/payload.js';
export {
  classifyJobFailure,
  formatJobErrorCode,
  type ClassifiedJobFailure,
} from './jobs/failures.js';
export { computeBackoffMs, type BackoffPolicy } from './jobs/backoff.js';
export { jobCorrelation, type JobCorrelation } from './jobs/correlation.js';
export {
  FINALIZATION_FAILURE_CODES,
  finalizationError,
  isFinalizationFailureCode,
  type FinalizationFailureCode,
} from './jobs/finalization-failures.js';
export {
  AUDIT_CHAIN_SCHEMA_VERSION,
  canonicalizeJsonValue,
  computeAuditEventHash,
  genesisPreviousEventHash,
  serializeCanonicalJson,
  sha256Hex as sha256HexCanonical,
  toCanonicalAuditEventV1,
  type AuditEventHashInput,
  type CanonicalAuditEventV1,
  type CanonicalJson,
} from './audit/canonical.js';
export { assertApprovedAuditPayload } from './audit/payload.js';
export {
  AUDIT_VERIFICATION_FAILURE_CODES,
  AUDIT_VERIFICATION_WARNING_CODES,
  isAuditVerificationFailureCode,
  type AuditVerificationFailure,
  type AuditVerificationFailureCode,
  type AuditVerificationReport,
  type AuditVerificationWarning,
  type AuditVerificationWarningCode,
  type OrganizationAuditVerificationReport,
} from './audit/verification.js';
export type {
  AuditCheckpoint,
  CheckpointPutResult,
  ImmutableCheckpointStore,
} from './ports/checkpoint-store.js';
export type { FeatureFlagContext, FeatureFlagPort } from './ports/feature-flags.js';
export type {
  AuditVerificationAlert,
  AuditVerificationAlertSink,
  AuditVerificationMetrics,
  AuditVerificationMetricsSnapshot,
} from './ports/audit-verification.js';
export {
  isJobQueueStale,
  type ClaimedOutboxWork,
  type JobQueueDepth,
  type JobQueueHealth,
  type JobQueueMetrics,
  type JobQueueMetricsSnapshot,
  type OutboxClaimer,
  type OutboxJobHandler,
} from './ports/job-queue.js';
