export {
  APPLICATION_ERROR_KIND,
  ApplicationError,
  AuthenticationError,
  AuthorizationError,
  ConflictError,
  ExternalServiceError,
  IntegrityError,
  InvalidStateTransitionError,
  isApplicationError,
  NotFoundError,
  RateLimitError,
  ValidationError,
  type ApplicationErrorDetails,
  type ApplicationErrorKind,
} from './errors.js';
export {
  DOCUMENT_STATES,
  DOCUMENT_REVISION_KINDS,
  SIGNER_STATUSES,
  SIGNING_SESSION_STATUSES,
  SIGNATURE_FIELD_TYPES,
  AUDIT_ACTOR_TYPES,
  AUDIT_EVENT_TYPES,
  OUTBOX_STATUSES,
  BACKGROUND_JOB_STATUSES,
  IDEMPOTENCY_PRINCIPAL_TYPES,
  type AccountUser,
  type AuditEvent,
  type AuditActorType,
  type AuditEventType,
  type BackgroundJob,
  type BackgroundJobStatus,
  type ConsentRecord,
  type Document,
  type DocumentRevision,
  type DocumentRevisionKind,
  type DocumentState,
  type FinalizedArtifact,
  type IdempotencyPrincipalType,
  type IdempotencyRecord,
  type Organization,
  type OrganizationMembership,
  type OutboxEvent,
  type OutboxStatus,
  type SignatureField,
  type SignatureFieldType,
  type Signer,
  type SignerStatus,
  type SigningSession,
  type SigningSessionStatus,
} from './entities.js';
export {
  DOCUMENT_TRANSITIONS,
  assertDocumentTransition,
  canTransitionDocument,
  isDocumentState,
} from './document-lifecycle.js';
export {
  isOpaqueId,
  organizationContext,
  requireOpaqueId,
  requireOrganizationId,
  type OrganizationContext,
} from './organization-context.js';
export {
  actorId,
  actorType,
  MEMBERSHIP_ROLES,
  organizationContextFromActor,
  type AccountUserActor,
  type MembershipRole,
  type RequestActor,
  type SignerActor,
  type SystemActor,
  type WorkerActor,
} from './request-actor.js';
export {
  AUDIT_GENESIS_PREVIOUS_EVENT_HASH,
  assertTenantObjectKey,
  tenantObjectKey,
  tenantObjectKeyPrefix,
} from './object-keys.js';
export type {
  Clock,
  Hashing,
  IdGenerator,
  AuditWriter,
  JobPublishInput,
  JobPublisher,
  NewAuditEvent,
  ObjectStorage,
  SigningTokenGenerator,
  SigningTokenHasher,
  StoredObjectMetadata,
} from './ports/services.js';
export {
  AUTHORIZATION_ACTIONS,
  type AuthorizationAction,
  type AuthorizationPolicy,
  type AuthorizationResource,
} from './ports/authorization.js';
export type {
  AuditLogRepository,
  BackgroundJobRepository,
  ConsentRecordRepository,
  DocumentRepository,
  DocumentRevisionRepository,
  FinalizedArtifactRepository,
  IdempotencyRecordRepository,
  MembershipRepository,
  OrganizationRepository,
  OutboxEventRepository,
  SignatureFieldRepository,
  SignerRepository,
  SigningSessionRepository,
  SigningTokenLookup,
  TenantRepositories,
  UserRepository,
} from './ports/repositories.js';
export { TENANT_REPOSITORY_TYPE_GUARDS } from './ports/repositories.js';
export type { TransactionScope, UnitOfWork } from './ports/unit-of-work.js';
export type { AssertTenantScopedRepository } from './ports/tenant-scope.js';
